package main

import (
	"testing"
)

var example1 string = `............
........0...
.....0......
.......0....
....0.......
......A.....
............
............
........A...
.........A..
............
............`

var exampleT string = `T.........
...T......
.T........
..........
..........
..........
..........
..........
..........
..........`

func TestPart1(t *testing.T) {
	want := 14
	res := part_01(example1)

	if res != want {
		t.Fatalf("part_01 expected %d got: %d", want, res)
	}
}

func TestPart2(t *testing.T) {
	want := 34
	res := part_02(example1)

	if res != want {
		t.Fatalf("part_02 expected %d got: %d", want, res)
	}
}

func TestPart2withT(t *testing.T) {
	want := 9
	res := part_02(exampleT)

	if res != want {
		t.Fatalf("part_02 expected %d got: %d", want, res)
	}
}
